# Generated by Django 2.1.7 on 2019-03-24 11:13

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to=movie.models.movie_directory_path)),
                ('movie_title', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_country', models.CharField(max_length=50)),
                ('user_producer', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
